Networking examples: Call private Cloud Function from onprem
terraform-google-modules/cloud-foundation-fabric pull request #278
Opened 2021-07-19 14:45 UTC by andgandolfi

Networking examples: Add "Calling a private Cloud Function from On-premises" example

2021-07-19 15:37 UTC, ludoo commented
/gcbrun

2021-07-19 15:56 UTC, juliocc requested changes
Left a few comments.

2021-07-20 05:55 UTC, andgandolfi commented on networking/private-cloud-function-from-onprem/main.tf
> +resource "google_compute_global_address" "psc-address" {
Currently the net-address module doesn't support this kind of "google_compute_global_address" resources

2021-07-20 06:00 UTC, ludoo commented on networking/private-cloud-function-from-onprem/main.tf
>  module "bucket-functions" {
You can use `bucket-config` in the function module to auto-create bucket, and skip the GCS module.

2021-07-20 06:00 UTC, ludoo commented on networking/private-cloud-function-from-onprem/main.tf
>    name            = var.onprem_project_id
I would use a single `projects_ids` variable, with `gcp` and `onprem` attributes.

2021-07-20 06:00 UTC, ludoo commented on networking/private-cloud-function-from-onprem/main.tf
> +      name               = "onprem-subnet"
`-subnet` is redundant in a subnet name, but I would use a prefix to make sure th ename does not clash with pre-existing subnets (and also use the prefix for all other resource names).

2021-07-20 06:00 UTC, ludoo commented on networking/private-cloud-function-from-onprem/main.tf
> -  admin_ranges         = ["0.0.0.0/0"]
You can use the subnet range here, or skip the attribute entirely. You don't need to specify attributes who already have empty defaults.

2021-07-20 06:00 UTC, ludoo commented on networking/private-cloud-function-from-onprem/main.tf
> +        internal = [cidrhost(var.ip_ranges.onprem, 2)]
why do you need to specify the IP?

2021-07-20 06:00 UTC, juliocc commented on networking/private-cloud-function-from-onprem/main.tf
> +resource "google_compute_global_address" "psc-address" {
exactly ;)

2021-07-20 09:44 UTC, andgandolfi reviewed
Fixed the suggested changes

2021-07-20 09:46 UTC, ludoo approved these changes

2021-07-20 09:51 UTC, juliocc approved these changes

2021-07-20 09:54 UTC, merged

2021-07-20 09:54 UTC, juliocc commented
@andgandolfi thanks for the PR

As an enhancement, you can update the net-address module to support PSC (#279) endpoints and use that to reserve the address