Allow using gVNIC in compute-vm (#211)
terraform-google-modules/cloud-foundation-fabric pull request #284
Opened 2021-07-25 15:20 UTC by lgandras

This only adds the parameter `nic_type` to compute-vm. I would consider creating a module for compute images in order to catch the issue that certain flags are added implicitly to images when enabling `GVNIC` as a guest os feature.

2021-07-25 15:55 UTC, lgandras commented
In order to merge underlying enabled `guest_os_features` of public images with the ones of the custom image, we need a patch: https://github.com/hashicorp/terraform-provider-google/issues/9630

2021-07-26 06:11 UTC, juliocc requested changes

2021-07-26 06:11 UTC, juliocc commented on modules/compute-vm/README.md
> +This example shows how to enable [gVNIC](https://cloud.google.com/compute/docs/networking/using-gvnic) on your VM by customizing a `cos` image. Given that gVNIC needs to be enabled as an instance con
s/implicitl/implicitly/

2021-07-26 06:12 UTC, juliocc commented on modules/compute-vm/README.md
> +This example shows how to enable [gVNIC](https://cloud.google.com/compute/docs/networking/using-gvnic) on your VM by customizing a `cos` image. Given that gVNIC needs to be enabled as an instance con
and s/as an guest os/a a guest OS/

2021-07-26 06:47 UTC, ludoo submitted a review, later dismissed
I'm not sure the `network_interfaces` variable is the right place for this, as it will force users to specify an extra bool every time. I have the same issue with alias ips and addresses BTW.

@juliocc WDYT of an extra variable, something like `network_options`, where users can specify just the overrides they need?

2021-07-26 07:10 UTC, juliocc commented
I was thinking the same thing.  I've been waiting for [optional attributes](https://www.terraform.io/docs/language/expressions/type-constraints.html#experimental-optional-object-type-attributes) to make the interface simpler but it's been stuck in experimental for a while.

IMO `network_interfaces` is the right place but I agree that it's becoming cumbersome to pass in a bunch of nulls. My problem with an override like `network_options` is that once optional attributes become stable, we'll probably end up reverting to the current interface.

2021-07-26 07:41 UTC, ludoo commented
> I was thinking the same thing. I've been waiting for [optional attributes](https://www.terraform.io/docs/language/expressions/type-constraints.html#experimental-optional-object-type-attributes) to make the interface simpler but it's been stuck in experimental for a while.

Once/if that lands, we'll have to go over each module I guess... :)

> IMO `network_interfaces` is the right place but I agree that it's becoming cumbersome to pass in a bunch of nulls. My problem with an override like `network_options` is that once optional attributes become stable, we'll probably end up reverting to the current interface.

Well, I would much rather have to do it twice (the second time with all other modules), than overload network interfaces for an unknown amount of time. WDYT? I can give it a shot and we can discuss on a PR.

2021-07-26 07:49 UTC, juliocc commented
SGTM. Lets give it a try.

On Mon, Jul 26, 2021, 9:41 AM Ludovico Magnocavallo <
***@***.***> wrote:

> I was thinking the same thing. I've been waiting for optional attributes
> <https://www.terraform.io/docs/language/expressions/type-constraints.html#experimental-optional-object-type-attributes>
> to make the interface simpler but it's been stuck in experimental for a
> while.
>
> Once/if that lands, we'll have to go over each module I guess... :)
>
> IMO network_interfaces is the right place but I agree that it's becoming
> cumbersome to pass in a bunch of nulls. My problem with an override like
> network_options is that once optional attributes become stable, we'll
> probably end up reverting to the current interface.
>
> Well, I would much rather have to do it twice (the second time with all
> other modules), than overload network interfaces for an unknown amount of
> time. WDYT? I can give it a shot and we can discuss on a PR.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/terraform-google-modules/cloud-foundation-fabric/pull/284#issuecomment-886457835>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAYRPMVJPRX5HF3X5JVHR3TZUGULANCNFSM5A6UJJ5Q>
> .
>

2021-08-10 08:11 UTC, juliocc commented
@lgandras optional is nice but it's an experimental feature. I think the idea was to move the secondary ranges and nic type to a new variable.

2021-08-10 12:11 UTC, lgandras commented
You're right. Since `network_options` is a separate variable and `network_interfaces` is a list, should we make `network_options` a map indexed by interface name?

2021-08-10 12:24 UTC, lgandras commented
And sorry, by interface name I mean the interface index.

2021-08-11 08:15 UTC, juliocc commented
I see two options

Either
```hcl
module "simple-vm-example" {
  // ...
  network_interfaces = [{
    network    = var.vpc.self_link
    subnetwork = var.subnet.self_link
    nat        = false
    addresses  = null
  }]
  network_interface_options = {
    0 = {
      alias_ips = null,
      nic_type = "GVNIC"
    }
  }
}
```

or 
```hcl
module "simple-vm-example" {
  // ...
  network_interfaces = [{
    network    = var.vpc.self_link
    subnetwork = var.subnet.self_link
    nat        = false
    addresses  = null
  }]
  network_interface_type = {
    0 = "GVNIC"
  }
  network_interface_alias_ips = {
    0 = ...
  }
}
```

And maybe even `addresses` can be moved out of `network_interfaces` since it's not used that often.

@ludoo wdyt?

2021-08-11 08:24 UTC, ludoo commented
> @ludoo wdyt?

The first one limits proliferation of variables, but is less convenient if we force users to specify all parameters to change a single one. Not really sure which one is best, but I know I would like to move `addresses` out of the `network_interfaces` part.

2021-08-11 08:37 UTC, juliocc commented
I think the first option is a reasonable compromise at least until optional() becomes stable

2021-11-07 22:44 UTC, lgandras commented
Regarding the following error:
```
E       tftest.TerraformTestError: Error running command plan: 1  
E       Error: error retrieving image information: Get "https://compute.googleapis.com/compute/v1/projects/cos-cloud/global/images/family/cos-89-lts?alt=json&prettyPrint=false": private key should be a PEM or plain PKCS1 or PKCS8; parse error: asn1: syntax error: sequence truncated
E       
E         with data.google_compute_image.cos,
E         on main.tf line 1, in data "google_compute_image" "cos":
E          1: data "google_compute_image" "cos" {
```
The example in the README has a data resource. This one needs credentials to talk to GCP. I assume the error is because github is trying to authenticate using `.github/workflows/fake-key.json`. Should I just hardcode the `module.vm-with-gvnic.boot_disk.image` rather than referencing it from a data source?

2021-11-08 08:56 UTC, juliocc commented
yeah, just set `source-image` to `cos-89-lts/cos-cloud`.

2021-11-08 13:44 UTC, juliocc approved these changes

2021-11-08 13:45 UTC, merged