Added support for Stateful Managed Instance Groups
terraform-google-modules/cloud-foundation-fabric pull request #367
Opened 2021-11-23 16:28 UTC by stenio123

Supporting both stateful disks for all instances or for specific instances of the Managed Instance Group as documented [here](https://cloud.google.com/compute/docs/instance-groups/configuring-stateful-disks-in-migs)

2021-11-23 20:50 UTC, caiotavaresdito commented
Hi @stenio123, thank you for your contribution. It looks like the build fail due Terraform linting (fmt) and also the variables.tf should be sorted alphabetically.

2021-11-24 10:33 UTC, ludoo requested changes

2021-11-24 10:33 UTC, ludoo commented on modules/compute-mig/variables.tf
> +variable "minimal_action" {
Can we bundle these two variables in a single `upate_config` variable?

2021-11-24 10:33 UTC, ludoo commented on modules/compute-mig/variables.tf
> +variable "name_instance_config" {
I would bundle all four stateful-related variables in a single `stateful_config` one, with four attributes: `name`, `destroy_state`, `group_policy`, `instance_policy`. I'm not entirely clear how do you select the instance to attach an instance policy too, by positional argument or instance name?

2021-11-29 20:23 UTC, stenio123 commented
Thank you for the quick feedback. Looking into it.

Regarding the tests on tests/examples, does it use the *# tftest:modules=2:resources=2* at the bottom of the test? 
No idea where that came from in the earlier examples :-D

2021-12-02 18:09 UTC, stenio123 commented
@ludoo I really like your idea of bundling the stateful config variables, however I am running into all sorts of issues managing this complex object... you can check the ongoing discussion here https://discuss.hashicorp.com/t/loop-with-conditional-using-object-known-only-after-apply-oh-my/32639

Is there somewhere in the repo where you might have seen a similar situation that I can use as an example? I am concerned about overcomplicating things unnecessarily. Thanks!

2021-12-02 20:23 UTC, ludoo commented
Hey, thanks for spending time on this! This type of error is nasty, basically the rule is keys used in for_each need to be static (i.e. not computed at runtime), while values can be dynamic. I can try and have a look at it tomorrow, don't go crazy on this!

2021-12-03 16:57 UTC, stenio123 commented
Thank you! I think I got it after the latest reply on the Hashicorp forum, at least all tests are passing :-)

Let me stress test it a bit and clean up everything and will update today after lunch. The only thing is I believe I might still have the error on tests/examples/test_plan.py since I dont really understand where it gets the values from. Will do some digging before pushing.

2021-12-03 19:56 UTC, ludoo reviewed
Thanks *a lot* for this. I dropped a couple comments, then it might be good to go!

2021-12-03 19:56 UTC, ludoo commented on modules/compute-mig/main.tf
> +  for_each = try(var.stateful_config.per_instance_config, tomap({}))
nit: you can skip `tomap` and only `{}`.

2021-12-03 19:56 UTC, ludoo commented on modules/compute-mig/main.tf
> +  minimal_action                   = each.value.update_config.minimal_action
Would it make sense to guard against the user passing a `null` value for `update_config`? I skimmed the resource docs, and everything seems to be optional except for `name` and `instance_group_manager`. If that's so, we should wrap in `try`.

2021-12-08 17:11 UTC, stenio123 commented
Hello I made the requested changes and regular tests passing. Questions -

1- Could you please advise where I can find "check_documentation.py"? I checked the ci folder and have no idea what linting tests are being made, so dont know how to address the error
2- Related to that, not sure what is expected from "tests\examples"

Thanks!

2021-12-08 18:57 UTC, ludoo commented
Sorry, I should have explained earlier. :)

The READMEs are checked against the output of `tools/tfdoc.py`, which creates and injects the vars/outputs tables present at the bottom of each README file. If you're ok with creating a Python virtualenv and installe requirements from the `tools` folder, just run `tfdoc` from the root folder and pass the module's directory as its only argument.

As for examples, they are automatically run as tests, the `tftest` comment in them states the number of resources and modules used in plan.

If you prefer me to do the small fixes above, we can merge this into a branch, and I'll then do them myself before branching to master. No big deal if you prefer this way of course!

2021-12-08 19:10 UTC, ludoo commented on modules/compute-mig/main.tf
> +  minimal_action                   = try(each.value.update_config.minimal_action)
I'm reasonably sure you need to explicitly specifiy `null`: `try(..., null)`

2021-12-15 13:13 UTC, ludoo approved these changes

2021-12-15 13:56 UTC, merged